"""把项目生成的 Abaqus 根 deck 展开为单个可搬移的 INP 文件。

项目默认使用 ``physical.inp`` + ``blocks/`` + ``ingredients/``。本脚本只做文本展开，
不修改源文件，也不启动 Abaqus。输出文件必须不存在，避免覆盖已有证据。

    pixi run -- python -B scripts/export_flat_inp.py \
        work/para_aly/Coarse/T0p01/MS9/diverse_28/abaqus/physical.inp \
        work/inp_exports_<attempt>/diverse_28_Coarse_T0p01_MS9.inp
"""
from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


_INCLUDE = re.compile(
    r"^\s*\*include\s*,\s*input\s*=\s*(?:\"([^\"]+)\"|'([^']+)'|([^,]+?))\s*$",
    re.IGNORECASE,
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def flatten(source: Path) -> tuple[str, list[str]]:
    """Return the expanded deck text and included paths relative to the deck root."""
    source = source.resolve()
    root = source.parent
    included: list[str] = []

    def expand(path: Path, stack: tuple[Path, ...]) -> list[str]:
        path = path.resolve()
        if path in stack:
            chain = " -> ".join(item.name for item in stack + (path,))
            raise RuntimeError(f"检测到循环 *Include：{chain}")
        if not path.is_file():
            raise FileNotFoundError(f"找不到 *Include 文件：{path}")
        try:
            relative = path.relative_to(root).as_posix()
        except ValueError as exc:
            raise RuntimeError(f"*Include 超出根 deck 目录，拒绝导出：{path}") from exc

        output: list[str] = []
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            match = _INCLUDE.match(line)
            if match is None:
                output.append(line)
                continue
            name = next(value.strip() for value in match.groups() if value is not None)
            child = (root / name).resolve()
            try:
                child_relative = child.relative_to(root).as_posix()
            except ValueError as exc:
                raise RuntimeError(f"*Include 超出根 deck 目录，拒绝导出：{name}") from exc
            included.append(child_relative)
            output.append(f"** BEGIN FLATTENED INCLUDE: {child_relative}")
            output.extend(expand(child, stack + (path,)))
            output.append(f"** END FLATTENED INCLUDE: {child_relative}")
        return output

    lines = [
        "** Standalone Abaqus input file generated by scripts/export_flat_inp.py.",
        f"** Source root deck: {source.name}",
        f"** Source root SHA256: {_sha256(source)}",
    ]
    lines.extend(expand(source, ()))
    return "\n".join(lines) + "\n", included


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="根 deck，通常是 abaqus/physical.inp")
    parser.add_argument("output", type=Path, help="要创建的独立 .inp；必须尚不存在")
    args = parser.parse_args()

    source = args.source.resolve()
    output = args.output.resolve()
    if source.suffix.lower() != ".inp" or output.suffix.lower() != ".inp":
        parser.error("source 和 output 都必须是 .inp 文件")
    if output.exists():
        parser.error(f"输出已存在，拒绝覆盖：{output}")

    text, included = flatten(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    print(f"已生成独立 INP：{output}")
    print(f"已展开 {len(included)} 个 include，输出 {output.stat().st_size} bytes")
    print(f"SHA256：{_sha256(output)}")


if __name__ == "__main__":
    main()
